name: yt_ui_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  objectbox: ^2.2.1
  objectbox_flutter_libs: ^2.2.1
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  youtube_player_flutter: ^8.1.2
  bloc: any
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  objectbox_generator: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/youtube.svg
    - assets/images/img.jpg
    - assets/images/thumbnailIcon.jpg
    - assets/icons/ytcompass.png
    
  fonts:
    - family: KenyanCoffee
      fonts:
      - asset: assets/fonts/kenyan_coffee/kenyancoffeerg.otf
    - family: YtSans
      fonts:
      - asset: assets/fonts/youtube-sans-cufonfonts/YouTubeSansRegular.otf
        weight: 400
      - asset: assets/fonts/youtube-sans-cufonfonts/YouTubeSansMedium.otf
        weight: 500